import {
  AuthorizationRole,
  EmployeeRecord,
  IncidentRecord,
  IncidentSeverity,
  KnowledgeAsset,
  OnboardingChecklist,
  TaskStatus,
  TeamEscalationContact,
  TimesheetRecord,
  TimesheetStatus,
} from "./types.js";

export const SYNTHETIC_EMPLOYEES: Record<string, EmployeeRecord> = {
  "EMP-2026-001": {
    employee_id: "EMP-2026-001",
    google_subject: "google-sub-rahul-001",
    email: "rahul.sharma@company.com",
    name: "Rahul Sharma",
    department: "Engineering",
    team: "Payments",
    job_role: "Software Engineer I",
    authorization_role: AuthorizationRole.EMPLOYEE,
    manager_id: "EMP-2026-010",
    location: "Seattle, WA",
    joining_date: "2026-09-01",
    onboarding_status: "IN_PROGRESS",
    is_day_one: true,
    assigned_buddy_name: "Priya Nair",
    assigned_buddy_email: "priya.nair@company.com",
    onboarding_track: "Backend",
  },
  "EMP-2026-002": {
    employee_id: "EMP-2026-002",
    google_subject: "google-sub-maya-002",
    email: "maya.lin@company.com",
    name: "Maya Lin",
    department: "Infrastructure",
    team: "Platform",
    job_role: "Cloud Infrastructure Intern",
    authorization_role: AuthorizationRole.EMPLOYEE,
    manager_id: "EMP-2026-005",
    location: "San Francisco, CA",
    joining_date: "2026-09-01",
    onboarding_status: "IN_PROGRESS",
    is_day_one: true,
    assigned_buddy_name: "David Miller",
    assigned_buddy_email: "david.miller@company.com",
    onboarding_track: "Platform",
  },
  "EMP-2026-003": {
    employee_id: "EMP-2026-003",
    google_subject: "google-sub-liam-003",
    email: "liam.vance@company.com",
    name: "Liam Vance",
    department: "Engineering",
    team: "Payments",
    job_role: "Software Engineer II",
    authorization_role: AuthorizationRole.EMPLOYEE,
    manager_id: "EMP-2026-010",
    location: "Austin, TX",
    joining_date: "2026-08-15",
    onboarding_status: "IN_PROGRESS",
    is_day_one: false,
    assigned_buddy_name: "Priya Nair",
    assigned_buddy_email: "priya.nair@company.com",
    onboarding_track: "Backend",
  },
  "EMP-2026-004": {
    employee_id: "EMP-2026-004",
    google_subject: "google-sub-carlos-004",
    email: "carlos.s@company.com",
    name: "Carlos Santana",
    department: "Data Platforms",
    team: "DataOps",
    job_role: "Senior Staff Data Engineer",
    authorization_role: AuthorizationRole.EMPLOYEE,
    manager_id: "EMP-2026-005",
    location: "New York, NY",
    joining_date: "2024-05-10",
    onboarding_status: "COMPLETED",
    is_day_one: false,
    assigned_buddy_name: null,
    assigned_buddy_email: null,
    onboarding_track: "DataOps",
  },
  "EMP-2026-005": {
    employee_id: "EMP-2026-005",
    google_subject: "google-sub-alex-005",
    email: "alex.chen@company.com",
    name: "Alex Chen",
    department: "Infrastructure",
    team: "Platform",
    job_role: "Director of Platform Engineering",
    authorization_role: AuthorizationRole.MANAGER,
    manager_id: null,
    location: "San Francisco, CA",
    joining_date: "2023-01-15",
    onboarding_status: "COMPLETED",
    is_day_one: false,
    assigned_buddy_name: null,
    assigned_buddy_email: null,
    onboarding_track: "Platform",
  },
  "EMP-2026-006": {
    employee_id: "EMP-2026-006",
    google_subject: "google-sub-priya-006",
    email: "priya.nair@company.com",
    name: "Priya Nair",
    department: "Engineering",
    team: "Payments",
    job_role: "Staff Software Engineer & Tech Lead",
    authorization_role: AuthorizationRole.EMPLOYEE,
    manager_id: "EMP-2026-010",
    location: "Seattle, WA",
    joining_date: "2023-08-01",
    onboarding_status: "COMPLETED",
    is_day_one: false,
    assigned_buddy_name: null,
    assigned_buddy_email: null,
    onboarding_track: "Backend",
  },
  "EMP-2026-007": {
    employee_id: "EMP-2026-007",
    google_subject: "google-sub-elena-007",
    email: "elena.r@company.com",
    name: "Elena Rostova",
    department: "Security",
    team: "Platform",
    job_role: "Senior SecOps & Cloud IAM Engineer",
    authorization_role: AuthorizationRole.EMPLOYEE,
    manager_id: "EMP-2026-005",
    location: "Boston, MA",
    joining_date: "2024-01-10",
    onboarding_status: "COMPLETED",
    is_day_one: false,
    assigned_buddy_name: null,
    assigned_buddy_email: null,
    onboarding_track: "Platform",
  },
  "EMP-2026-008": {
    employee_id: "EMP-2026-008",
    google_subject: "google-sub-marcus-008",
    email: "marcus.v@company.com",
    name: "Marcus Vance",
    department: "IT Services",
    team: "IT",
    job_role: "Lead IT Systems Administrator",
    authorization_role: AuthorizationRole.IT,
    manager_id: null,
    location: "Chicago, IL",
    joining_date: "2023-11-01",
    onboarding_status: "COMPLETED",
    is_day_one: false,
    assigned_buddy_name: null,
    assigned_buddy_email: null,
    onboarding_track: "General",
  },
  "EMP-2026-009": {
    employee_id: "EMP-2026-009",
    google_subject: "google-sub-amanda-009",
    email: "amanda.w@company.com",
    name: "Amanda Walker",
    department: "People Operations",
    team: "HR",
    job_role: "Senior People Ops Specialist",
    authorization_role: AuthorizationRole.HR,
    manager_id: null,
    location: "New York, NY",
    joining_date: "2023-04-15",
    onboarding_status: "COMPLETED",
    is_day_one: false,
    assigned_buddy_name: null,
    assigned_buddy_email: null,
    onboarding_track: "General",
  },
  "EMP-2026-010": {
    employee_id: "EMP-2026-010",
    google_subject: "google-sub-sarah-010",
    email: "sarah.j@company.com",
    name: "Sarah Jenkins",
    department: "Engineering",
    team: "Payments",
    job_role: "Engineering Manager - Payments",
    authorization_role: AuthorizationRole.MANAGER,
    manager_id: null,
    location: "Seattle, WA",
    joining_date: "2022-09-01",
    onboarding_status: "COMPLETED",
    is_day_one: false,
    assigned_buddy_name: null,
    assigned_buddy_email: null,
    onboarding_track: "Backend",
  },
};

export const SYNTHETIC_ONBOARDING_CHECKLISTS: Record<string, OnboardingChecklist> = {
  "EMP-2026-001": {
    employee_id: "EMP-2026-001",
    track: "Backend",
    tasks: [
      {
        task_id: "TASK-001-SEC",
        title: "Complete Corporate Security & Data Privacy Training",
        description: "Review security policies, 2FA setup, and complete the compliance module.",
        status: TaskStatus.COMPLETED,
        due_days_after_start: 1,
        completed_at: "2026-09-01T10:30:00Z",
        category: "Security & Compliance",
        action_link: "https://learning.internal.company.com/courses/sec-2026",
      },
      {
        task_id: "TASK-001-ENV",
        title: "Set up Local Dev Environment & Cloud SQL Proxy",
        description: "Install gcloud CLI, Docker, and configure Cloud SQL Auth Proxy for PostgreSQL staging.",
        status: TaskStatus.PENDING,
        due_days_after_start: 2,
        category: "Development Setup",
        action_link: "gs://patchamomma-knowledge-mesh/runbooks/dev_environment_setup.md",
      },
      {
        task_id: "TASK-001-BUDDY",
        title: "Schedule 1:1 Intro with Onboarding Buddy (Priya Nair)",
        description: "Connect with Priya for payments architecture overview and team introduction.",
        status: TaskStatus.PENDING,
        due_days_after_start: 3,
        category: "Team Integration",
        action_link: "mailto:priya.nair@company.com",
      },
      {
        task_id: "TASK-001-GIT",
        title: "Submit first sandbox PR to payments-core repo",
        description: "Clone repository, make standard JSON logger improvement, and open test PR.",
        status: TaskStatus.PENDING,
        due_days_after_start: 5,
        category: "First Milestone",
        action_link: "https://github.com/company/payments-core",
      },
    ],
    completed_count: 1,
    total_count: 4,
    next_pending_task: {
      task_id: "TASK-001-ENV",
      title: "Set up Local Dev Environment & Cloud SQL Proxy",
      description: "Install gcloud CLI, Docker, and configure Cloud SQL Auth Proxy for PostgreSQL staging.",
      status: TaskStatus.PENDING,
      due_days_after_start: 2,
      category: "Development Setup",
      action_link: "gs://patchamomma-knowledge-mesh/runbooks/dev_environment_setup.md",
    },
  },
  "EMP-2026-002": {
    employee_id: "EMP-2026-002",
    track: "Platform",
    tasks: [
      {
        task_id: "TASK-002-SEC",
        title: "Complete Corporate Security & Data Privacy Training",
        description: "Complete mandatory security basics and IAM access policies.",
        status: TaskStatus.PENDING,
        due_days_after_start: 1,
        category: "Security & Compliance",
        action_link: "https://learning.internal.company.com/courses/sec-2026",
      },
      {
        task_id: "TASK-002-GCP",
        title: "Configure Google Cloud SDK & GKE Cluster Access",
        description: "Set up gcloud auth and kubectl credentials for staging Kubernetes clusters.",
        status: TaskStatus.PENDING,
        due_days_after_start: 2,
        category: "Infrastructure Setup",
        action_link: "gs://patchamomma-knowledge-mesh/runbooks/kubernetes_cluster_triage.md",
      },
      {
        task_id: "TASK-002-BUDDY",
        title: "Schedule 1:1 Intro with Onboarding Buddy (David Miller)",
        description: "Introductory pairing session on infrastructure pipelines.",
        status: TaskStatus.PENDING,
        due_days_after_start: 3,
        category: "Team Integration",
        action_link: "mailto:david.miller@company.com",
      },
    ],
    completed_count: 0,
    total_count: 3,
    next_pending_task: {
      task_id: "TASK-002-SEC",
      title: "Complete Corporate Security & Data Privacy Training",
      description: "Complete mandatory security basics and IAM access policies.",
      status: TaskStatus.PENDING,
      due_days_after_start: 1,
      category: "Security & Compliance",
      action_link: "https://learning.internal.company.com/courses/sec-2026",
    },
  },
  "EMP-2026-003": {
    employee_id: "EMP-2026-003",
    track: "Backend",
    tasks: [
      {
        task_id: "TASK-003-SEC",
        title: "Complete Corporate Security & Data Privacy Training",
        description: "Compliance certification.",
        status: TaskStatus.COMPLETED,
        due_days_after_start: 1,
        category: "Security",
      },
      {
        task_id: "TASK-003-ENV",
        title: "Set up Local Dev Environment & Cloud SQL Proxy",
        description: "Setup postgres proxy and secrets.",
        status: TaskStatus.COMPLETED,
        due_days_after_start: 2,
        category: "Setup",
      },
      {
        task_id: "TASK-003-BUDDY",
        title: "Schedule 1:1 Intro with Onboarding Buddy",
        description: "1:1 with buddy.",
        status: TaskStatus.COMPLETED,
        due_days_after_start: 3,
        category: "Integration",
      },
      {
        task_id: "TASK-003-GIT",
        title: "Submit first sandbox PR to payments-core repo",
        description: "Open PR.",
        status: TaskStatus.PENDING,
        due_days_after_start: 5,
        category: "Milestone",
      },
    ],
    completed_count: 3,
    total_count: 4,
    next_pending_task: {
      task_id: "TASK-003-GIT",
      title: "Submit first sandbox PR to payments-core repo",
      description: "Open PR.",
      status: TaskStatus.PENDING,
      due_days_after_start: 5,
      category: "Milestone",
    },
  },
};

export const SYNTHETIC_TIMESHEETS: Record<string, TimesheetRecord[]> = {
  "EMP-2026-001": [
    {
      timesheet_id: "TS-2026-W36-001",
      employee_id: "EMP-2026-001",
      period_start: "2026-08-31",
      period_end: "2026-09-04",
      hours_logged: 32.0,
      status: TimesheetStatus.PENDING,
      due_date: "2026-09-04",
    },
  ],
  "EMP-2026-002": [
    {
      timesheet_id: "TS-2026-W36-002",
      employee_id: "EMP-2026-002",
      period_start: "2026-08-31",
      period_end: "2026-09-04",
      hours_logged: 40.0,
      status: TimesheetStatus.SUBMITTED,
      due_date: "2026-09-04",
    },
  ],
  "EMP-2026-003": [
    {
      timesheet_id: "TS-2026-W35-003",
      employee_id: "EMP-2026-003",
      period_start: "2026-08-24",
      period_end: "2026-08-28",
      hours_logged: 0.0,
      status: TimesheetStatus.OVERDUE,
      due_date: "2026-08-28",
    },
  ],
  "EMP-2026-004": [
    {
      timesheet_id: "TS-2026-W36-004",
      employee_id: "EMP-2026-004",
      period_start: "2026-08-31",
      period_end: "2026-09-04",
      hours_logged: 40.0,
      status: TimesheetStatus.APPROVED,
      due_date: "2026-09-04",
    },
  ],
};

export const SYNTHETIC_INCIDENTS: IncidentRecord[] = [
  {
    incident_id: "INC-2026-8801",
    created_by: "EMP-2026-003",
    category: "Database / Staging",
    summary: "Staging PostgreSQL connection reset under load",
    severity: IncidentSeverity.MEDIUM,
    status: "OPEN",
    assigned_team: "Platform",
    created_at: "2026-09-02T14:22:00Z",
  },
];

export const SYNTHETIC_TEAM_DIRECTORY: Record<string, TeamEscalationContact> = {
  "Cloud SQL": {
    domain: "Cloud SQL",
    primary_lead_name: "Alex Chen",
    primary_email: "alex.chen@company.com",
    primary_on_vacation: false,
    backup_lead_name: "David Miller",
    backup_email: "david.miller@company.com",
    backup_on_vacation: false,
    general_channel: "#help-infrastructure",
  },
  Kubernetes: {
    domain: "Kubernetes",
    primary_lead_name: "Elena Rostova",
    primary_email: "elena.r@company.com",
    primary_on_vacation: true,
    backup_lead_name: "Carlos Santana",
    backup_email: "carlos.s@company.com",
    backup_on_vacation: false,
    general_channel: "#help-kubernetes",
  },
  "IAM & Security": {
    domain: "IAM & Security",
    primary_lead_name: "Elena Rostova",
    primary_email: "elena.r@company.com",
    primary_on_vacation: true,
    backup_lead_name: "Marcus Vance",
    backup_email: "marcus.v@company.com",
    backup_on_vacation: true,
    general_channel: "#security-triage",
  },
  "Data Pipelines": {
    domain: "Data Pipelines",
    primary_lead_name: "Carlos Santana",
    primary_email: "carlos.s@company.com",
    primary_on_vacation: false,
    backup_lead_name: "Alex Chen",
    backup_email: "alex.chen@company.com",
    backup_on_vacation: false,
    general_channel: "#dataplat-support",
  },
};

export const SYNTHETIC_KNOWLEDGE_CATALOG: Record<string, KnowledgeAsset> = {
  "DOC-ALL-001": {
    document_id: "DOC-ALL-001",
    title: "Patchamomma 2026 Code of Conduct & Values",
    source: "People Operations",
    gcs_uri: "gs://patchamomma-knowledge-mesh/company/code_of_conduct_2026.md",
    team: "ALL",
    access_level: "employee",
    document_type: "POLICY",
    owner: "amanda.w@company.com",
    description: "Core company values, inclusive culture, and workplace ethics.",
    chunks: [
      {
        chunk_id: "CHK-ALL-001-1",
        document_id: "DOC-ALL-001",
        chunk_index: 0,
        content:
          "# Patchamomma 2026 Code of Conduct\nWe prioritize psychological safety, radical candor with empathy, and customer obsession.\nWorking hours are core-flexible (10am - 4pm local). Timesheets must be finalized by Friday 5pm.",
        team: "ALL",
        access_level: "employee",
      },
    ],
  },
  "DOC-ALL-002": {
    document_id: "DOC-ALL-002",
    title: "Enterprise Python & Structured Logging Standards",
    source: "Architecture Guild",
    gcs_uri: "gs://patchamomma-knowledge-mesh/engineering/logging_standards_2026.md",
    team: "ALL",
    access_level: "employee",
    document_type: "STANDARDS",
    owner: "priya.nair@company.com",
    description: "Requirements for structured JSON logging and naked exception handling.",
    chunks: [
      {
        chunk_id: "CHK-ALL-002-1",
        document_id: "DOC-ALL-002",
        chunk_index: 0,
        content:
          "# Corporate Coding Standards 2026\n1. Never use raw print(...) statements in production services. Always use logger.info(json.dumps(...)).\n2. All microservices communicate via Cloud Pub/Sub and Cloud SQL Postgres proxy with IAM auth.\n3. Functions must be fully type-hinted and pass lint checks.",
        team: "ALL",
        access_level: "employee",
      },
    ],
  },
  "DOC-PAY-001": {
    document_id: "DOC-PAY-001",
    title: "Payments Microservice Architecture & Event Ledger Blueprint",
    source: "Payments Architecture",
    gcs_uri: "gs://patchamomma-knowledge-mesh/payments/architecture_overview_2026.md",
    team: "Payments",
    access_level: "employee",
    document_type: "BLUEPRINT",
    owner: "priya.nair@company.com",
    description: "Cloud SQL transactional ledger, double-entry bookkeeping, and idempotency keys.",
    chunks: [
      {
        chunk_id: "CHK-PAY-001-1",
        document_id: "DOC-PAY-001",
        chunk_index: 0,
        content:
          "# Payments Architecture Blueprint\nEvery transaction creates an immutable event in the Double-Entry Ledger on Cloud SQL PostgreSQL.\nIdempotency-Key headers are strictly verified via Redis KV cache (TTL 24 hours).",
        team: "Payments",
        access_level: "employee",
      },
    ],
  },
  "DOC-PLT-001": {
    document_id: "DOC-PLT-001",
    title: "Kubernetes Cluster Triage & Cloud SQL Proxy Runbook",
    source: "Platform Engineering",
    gcs_uri: "gs://patchamomma-knowledge-mesh/platform/kubernetes_cluster_triage.md",
    team: "Platform",
    access_level: "employee",
    document_type: "RUNBOOK",
    owner: "alex.chen@company.com",
    description: "Standard operating procedures for GKE pod failures, Cloud SQL Auth Proxy sidecars, and Secret Manager sync.",
    chunks: [
      {
        chunk_id: "CHK-PLT-001-1",
        document_id: "DOC-PLT-001",
        chunk_index: 0,
        content:
          "# Kubernetes Cluster Triage Runbook\n1. Run `kubectl get pods -n payments` to identify CrashLoopBackOff containers.\n2. Ensure Cloud SQL Auth Proxy sidecar is running on port 5432 with correct Workload Identity.\n3. Verify Secret Manager IAM binding `roles/secretmanager.secretAccessor`.",
        team: "Platform",
        access_level: "employee",
      },
    ],
  },
  "DOC-MGR-001": {
    document_id: "DOC-MGR-001",
    title: "Performance Management & Compensation Guidelines",
    source: "People Operations",
    gcs_uri: "gs://patchamomma-knowledge-mesh/hr/compensation_guidelines_2026.pdf",
    team: "ALL",
    access_level: "manager",
    document_type: "GUIDE",
    owner: "amanda.w@company.com",
    description: "Managerial compensation bands, promotion cycles, and quarterly review frameworks.",
    chunks: [
      {
        chunk_id: "CHK-MGR-001-1",
        document_id: "DOC-MGR-001",
        chunk_index: 0,
        content:
          "# Managerial Compensation & Performance Guidelines\nConfidential to Managers and HR: Annual review cycles occur in October.\nPromotion packages require 2 peer reviews and director approval.",
        team: "ALL",
        access_level: "manager",
      },
    ],
  },
};

export const SYNTHETIC_KNOWLEDGE_INSIGHTS: Array<{
  insight_id: string;
  title: string;
  category: "POLICY" | "STANDARDS" | "RUNBOOK" | "BLUEPRINT" | "SECURITY";
  summary: string;
  team: string;
  access_level: string;
  effective_date: string;
  highlight_tag: string;
  gcs_uri: string;
  action_suggestion: string;
}> = [
  {
    insight_id: "INSIGHT-2026-001",
    title: "Mandatory Structured JSON Logging v2.4 Enforced",
    category: "STANDARDS",
    summary: "All microservices must emit logs formatted in RFC-5424 JSON with trace context. Naked print() statements will fail CI pipeline checks.",
    team: "ALL",
    access_level: "employee",
    effective_date: "2026-09-01",
    highlight_tag: "Active CI Gate",
    gcs_uri: "gs://patchamomma-knowledge-mesh/engineering/logging_standards_2026.md",
    action_suggestion: "Check your repository logging wrapper against Code Mentor standards.",
  },
  {
    insight_id: "INSIGHT-2026-002",
    title: "Cloud SQL Auth Proxy v2.1 Sidecar Requirement",
    category: "RUNBOOK",
    summary: "Direct PostgreSQL connections from GKE pods without the Cloud SQL Auth Proxy sidecar are deprecated as of Q3. Workload Identity is now required.",
    team: "Platform",
    access_level: "employee",
    effective_date: "2026-08-28",
    highlight_tag: "Infrastructure Notice",
    gcs_uri: "gs://patchamomma-knowledge-mesh/platform/kubernetes_cluster_triage.md",
    action_suggestion: "Review the Kubernetes cluster triage and proxy sidecar runbook.",
  },
  {
    insight_id: "INSIGHT-2026-003",
    title: "Double-Entry Ledger Idempotency Key Specification",
    category: "BLUEPRINT",
    summary: "Payments Guild has updated the idempotency window to 24 hours on Redis KV cluster with automated BigQuery reconciliation streaming.",
    team: "Payments",
    access_level: "employee",
    effective_date: "2026-09-04",
    highlight_tag: "Payments Guild",
    gcs_uri: "gs://patchamomma-knowledge-mesh/payments/architecture_overview_2026.md",
    action_suggestion: "Inspect the Idempotency-Key headers in payment request routes.",
  },
  {
    insight_id: "INSIGHT-2026-004",
    title: "Core Flexible Working Hours & Timesheet Finalization",
    category: "POLICY",
    summary: "Core collaboration hours are 10:00 AM - 4:00 PM local time. All weekly timesheets must be submitted by Friday 5:00 PM to ensure payroll accuracy.",
    team: "ALL",
    access_level: "employee",
    effective_date: "2026-09-01",
    highlight_tag: "People Ops Update",
    gcs_uri: "gs://patchamomma-knowledge-mesh/company/code_of_conduct_2026.md",
    action_suggestion: "Verify your current weekly timesheet status before end-of-week.",
  },
  {
    insight_id: "INSIGHT-2026-005",
    title: "Q4 Performance Calibration & Compensation Review Cycle",
    category: "POLICY",
    summary: "Managers must complete peer review syntheses and submit promotion calibration packages by October 15th for department review.",
    team: "ALL",
    access_level: "manager",
    effective_date: "2026-09-05",
    highlight_tag: "Confidential - Manager / HR",
    gcs_uri: "gs://patchamomma-knowledge-mesh/hr/compensation_guidelines_2026.pdf",
    action_suggestion: "Review managerial compensation bands and calibration schedules.",
  },
];

